modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="concoction"
version="1.0.0"
displayName="Concoction"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
credits="Sebsish, woofyboo"
authors="Sebsish, woofyboo"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.concoction]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.concoction]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



